/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "surface":                    "#ffffff",
        "surface-dim":                "#f8f8f8",
        "surface-bright":             "#ffffff",
        "surface-container-lowest":   "#ffffff",
        "surface-container-low":      "#ffffff",
        "surface-container":          "#ffffff",
        "surface-container-high":     "#f8f8f8",
        "surface-container-highest":  "#f0f0f0",
        "on-surface":                 "#1a1a2e",
        "on-surface-variant":         "#6b7280",
        "inverse-surface":            "#1a1a2e",
        "inverse-on-surface":         "#ffffff",
        "outline":                    "#e5e7eb",
        "outline-variant":            "#f3f4f6",
        "surface-variant":            "#f8f8f8",
        "surface-tint":               "#e63946",
        "primary":                    "#e63946",
        "on-primary":                 "#ffffff",
        "primary-container":          "#e63946",
        "on-primary-container":       "#ffffff",
        "inverse-primary":            "#ff6b6b",
        "secondary":                  "#22c55e",
        "on-secondary":               "#ffffff",
        "secondary-container":        "#dcfce7",
        "on-secondary-container":     "#166534",
        "tertiary":                   "#f59e0b",
        "on-tertiary":                "#ffffff",
        "tertiary-container":         "#fef3c7",
        "on-tertiary-container":      "#92400e",
        "error":                      "#ef4444",
        "on-error":                   "#ffffff",
        "error-container":            "#fee2e2",
        "on-error-container":         "#991b1b",
        "primary-fixed":              "#fecdd3",
        "primary-fixed-dim":          "#fda4af",
        "on-primary-fixed":           "#9f1239",
        "on-primary-fixed-variant":   "#be123c",
        "secondary-fixed":            "#bbf7d0",
        "secondary-fixed-dim":        "#86efac",
        "on-secondary-fixed":         "#14532d",
        "on-secondary-fixed-variant": "#166534",
        "tertiary-fixed":             "#fde68a",
        "tertiary-fixed-dim":         "#fcd34d",
        "on-tertiary-fixed":          "#78350f",
        "on-tertiary-fixed-variant":  "#92400e",
        "background":                 "#ffffff",
        "on-background":              "#1a1a2e",
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "sm": "0.25rem",
        "md": "0.5rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "2xl": "1rem",
        "full": "9999px"
      },
      spacing: {
        "space-xxs": "0.25rem",
        "space-xs": "0.5rem",
        "space-sm": "0.75rem",
        "space-md": "1rem",
        "space-lg": "1.25rem",
        "space-xl": "1.5rem",
        "space-2xl": "2rem",
        "space-3xl": "2.5rem",
        "gutter-mobile": "1rem",
        "gutter-desktop": "1.5rem",
        "card-pad-sm": "0.875rem",
        "card-pad-md": "1.25rem"
      },
      fontFamily: {
        "display-score": ["Outfit", "sans-serif"],
        "headline-xl": ["Outfit", "sans-serif"],
        "headline-lg": ["Outfit", "sans-serif"],
        "headline-md": ["Outfit", "sans-serif"],
        "stat-metric": ["Outfit", "sans-serif"],
        "body-lg": ["Plus Jakarta Sans", "sans-serif"],
        "body-md": ["Plus Jakarta Sans", "sans-serif"],
        "body-sm": ["Plus Jakarta Sans", "sans-serif"],
        "label-tactical": ["Space Grotesk", "monospace"],
        "label-badge": ["Space Grotesk", "monospace"]
      },
      fontSize: {
        "body-sm": ["12px", { lineHeight: "16px", fontWeight: "400" }],
        "body-md": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "display-score": ["48px", { lineHeight: "52px", letterSpacing: "-0.04em", fontWeight: "800" }],
        "label-badge": ["11px", { lineHeight: "14px", letterSpacing: "0.06em", fontWeight: "600" }],
        "body-lg": ["16px", { lineHeight: "24px", fontWeight: "500" }],
        "stat-metric": ["24px", { lineHeight: "28px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-lg": ["22px", { lineHeight: "28px", letterSpacing: "-0.01em", fontWeight: "700" }],
        "headline-xl": ["28px", { lineHeight: "34px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "label-tactical": ["13px", { lineHeight: "16px", letterSpacing: "0.04em", fontWeight: "700" }],
        "headline-md": ["18px", { lineHeight: "24px", fontWeight: "600" }]
      }
    },
  },
  plugins: [],
};
